// <auto-generated />
using KlimaOppgave.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KlimaOppgave.Migrations
{
    [DbContext(typeof(SporsmalDbContext))]
    [Migration("20221228194242_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("KlimaOppgave.Models.Innlegg", b =>
                {
                    b.Property<string>("InnleggId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Innhold")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tittel")
                        .HasColumnType("TEXT");

                    b.HasKey("InnleggId");

                    b.ToTable("Innlegg");
                });

            modelBuilder.Entity("KlimaOppgave.Models.Svar", b =>
                {
                    b.Property<int>("SvarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Innhold")
                        .HasColumnType("TEXT");

                    b.Property<string>("InnleggId")
                        .HasColumnType("TEXT");

                    b.HasKey("SvarId");

                    b.HasIndex("InnleggId");

                    b.ToTable("Svar");
                });

            modelBuilder.Entity("KlimaOppgave.Models.Svar", b =>
                {
                    b.HasOne("KlimaOppgave.Models.Innlegg", "Innlegg")
                        .WithMany("Svar")
                        .HasForeignKey("InnleggId");
                });
#pragma warning restore 612, 618
        }
    }
}
