// <auto-generated />
using System;
using KlimaOppgave.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KlimaOppgave.Migrations
{
    [DbContext(typeof(SporsmalDbContext))]
    partial class SporsmalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("KlimaOppgave.Models.Brukere", b =>
                {
                    b.Property<int>("BrukerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brukernavn")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Passord")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("BLOB");

                    b.HasKey("BrukerId");

                    b.ToTable("Brukere");
                });

            modelBuilder.Entity("KlimaOppgave.Models.Innlegg", b =>
                {
                    b.Property<int>("InnleggId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Innhold")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tittel")
                        .HasColumnType("TEXT");

                    b.HasKey("InnleggId");

                    b.ToTable("Innlegg");
                });

            modelBuilder.Entity("KlimaOppgave.Models.Svar", b =>
                {
                    b.Property<int>("SvarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Innhold")
                        .HasColumnType("TEXT");

                    b.Property<int>("InnleggId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("SvarId");

                    b.HasIndex("InnleggId");

                    b.ToTable("Svar");
                });

            modelBuilder.Entity("KlimaOppgave.Models.Svar", b =>
                {
                    b.HasOne("KlimaOppgave.Models.Innlegg", "Innlegg")
                        .WithMany("Svar")
                        .HasForeignKey("InnleggId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
